### ISSUE TITLE
Problems with BIOM file created by biomformat

### ISSUE THREAD

**Issue by akense** [joey711/biomformat#1] opened 2017-10-05 23:29 UTC
Hi Joey,
The BIOM files I create with `write_biom` aren't working with other software. Specifically, I've tried and failed to import into Qiime 2. Qiime 2 support pointed out that the format is 1.0.0-dev, and the BIOM support team says that "the most likely reason is that it is using `list` types instead of `str `for entries such as `matrix_type`." I'm using biomformat version 1.2.0, but I've also tried `write_biom` using biomformat version 1.4.0, and the output file looks the same. 

The biom file looks like this:
```
{`
	"id":{},
	"format":["Biological Observation Matrix 1.0.0-dev"],
	"format_url":["http://biom-format.org/documentation/format_versions/biom-1.0.html"],
	"type":["OTU table"],
	"generated_by":["biomformat 1.2.0"],
	"date":["2017-09-21 14:36:28"],
	"matrix_type":["dense"],
	"matrix_element_type":["int"],
	"shape":[5,6],
	"rows":[
		{"id":["GG_OTU_1"],"metadata":["k__Bacteria","p__Proteobacteria","c__Gammaproteobacteria","o__Enterobacteriales","f__Enterobacteriaceae","g__Escherichia","s__"]},
		{"id":["GG_OTU_2"],"metadata":["k__Bacteria","p__Cyanobacteria","c__Nostocophycideae","o__Nostocales","f__Nostocaceae","g__Dolichospermum","s__"]},
		{"id":["GG_OTU_3"],"metadata":["k__Archaea","p__Euryarchaeota","c__Methanomicrobia","o__Methanosarcinales","f__Methanosarcinaceae","g__Methanosarcina","s__"]},
		{"id":["GG_OTU_4"],"metadata":["k__Bacteria","p__Firmicutes","c__Clostridia","o__Halanaerobiales","f__Halanaerobiaceae","g__Halanaerobium","s__Halanaerobiumsaccharolyticum"]},
		{"id":["GG_OTU_5"],"metadata":["k__Bacteria","p__Proteobacteria","c__Gammaproteobacteria","o__Enterobacteriales","f__Enterobacteriaceae","g__Escherichia","s__"]}
		],
	"columns":[
		{"id":["Sample1"],"metadata":["CGCTTATCGAGA","CATGCTGCCTCCCGTAGGAGT","gut","human gut"]},
		{"id":["Sample2"],"metadata":["CATACCAGTAGC","CATGCTGCCTCCCGTAGGAGT","gut","human gut"]},
		{"id":["Sample3"],"metadata":["CTCTCTACCTGT","CATGCTGCCTCCCGTAGGAGT","gut","human gut"]},
		{"id":["Sample4"],"metadata":["CTCTCGGCCTGT","CATGCTGCCTCCCGTAGGAGT","skin","human skin"]},
		{"id":["Sample5"],"metadata":["CTCTCTACCAAT","CATGCTGCCTCCCGTAGGAGT","skin","human skin"]},
		{"id":["Sample6"],"metadata":["CTAACTACCAAT","CATGCTGCCTCCCGTAGGAGT","skin","human skin"]}
		],
	"data": [[0,0,1,0,0,0],
			 [5,1,0,2,3,1],
			 [0,0,1,4,2,0],
			 [2,1,1,0,0,1],
			 [0,1,1,0,0,0]]
}
```

This is the error output from Qiime 2:
```
Traceback (most recent call last):
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/bin/qiime", line 6, in <module>
    sys.exit(q2cli.__main__.qiime())
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/q2cli/tools.py", line 111, in import_data
    view_type=source_format)
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/qiime2/sdk/result.py", line 192, in import_data
    return cls._from_view(type_, view, view_type, provenance_capture)
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/qiime2/sdk/result.py", line 217, in _from_view
    result = transformation(view)
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/qiime2/core/transform.py", line 59, in transformation
    new_view = transformer(view)
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/qiime2/core/transform.py", line 207, in wrapped
    file_view = transformer(view)
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/q2_types/feature_table/_transformer.py", line 128, in _8
    data = _parse_biom_table_v100(ff)
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/q2_types/feature_table/_transformer.py", line 46, in _parse_biom_table_v100
    table = biom.Table.from_json(json.load(fh))
  File "/home/akense/programs/miniconda3/envs/qiime2.env.analysis/lib/python3.5/site-packages/biom_format-2.1.5-py3.5-linux-x86_64.egg/biom/table.py", line 3672, in from_json
    dtype = MATRIX_ELEMENT_TYPE[json_table['matrix_element_type']]
TypeError: unhashable type: 'list'
```

Any idea what is going on here? 
Thanks in advance for your help!

**Comment by seashore001x** [comment] 2017-10-16 16:57
I got the same question. The biom file converted using `write_biom` can`t be imported into qiime2.

**Comment by smdabdoub** [comment] 2017-10-27 21:16
The issue is that all the top-level metadata (in your case specifically, the matrix_element_type) need to be strings and not lists.

I forked the project and committed a fix: https://github.com/smdabdoub/biomformat/blob/master/R/IO-methods.R#L124

I'll submit a pull request, but until then you can install the fixed version via github as per the README:

`devtools::install_github("smdabdoub/biomformat")`

**Comment by smdabdoub** [comment] 2017-10-27 22:00
Another issue related to file validation is that the [jsonlite](https://github.com/jeroen/jsonlite) library turns decimals into integers if the fractional part is 0 (e.g. 10.0 -> 10). This will cause the biom validate-table script to fail with the message "Bad datatype in row" if matrix_element_type is set to "float".

I've opened an issue over there:

https://github.com/jeroen/jsonlite/issues/208

**Comment by smdabdoub** [comment] 2017-11-01 13:34
The jsonlite issue was resolved, and just required passing a parameter into the toJSON function. See all the fixes in pull request https://github.com/joey711/biomformat/pull/2.

**Comment by joey711** [comment] 2017-11-06 19:55
your PR has been merged into master

**Closed as completed by joey711** 2017-11-06 19:55 UTC

**Comment by CarlyMuletzWolz** [comment] 2018-04-11 19:36
Hi, I'm not sure whether this has been fixed or not. 

I did several analyses in R including subsetting my dataset. I would like to export the biom file so that I can use it in QIIME to generate relative abundance plots (much more streamlined in QIIME). The issue is I keep getting the same error as the original post. For instance, I'm was trying to convert from json to hdf5 to see if that would fix it using biom convert

#### These are the commands in R

library(devtools)
devtools::install_github("smdabdoub/biomformat")

otu <- as(otu_table(fnm_cfa), "matrix")
tax <- as(tax_table(fnm_cfa), "matrix")
b2 <- biomformat::make_biom(data = otu, observation_metadata = tax)

biomformat::write_biom(b2, 'test.biom')

####  This is is the command using macqiime with biom convert
biom convert -i test.biom -o test_hdf5.biom --to-hdf5 --table-type="OTU table"

#### and this is the error from macqiime

Traceback (most recent call last):
  File "/macqiime/anaconda/bin/pyqi", line 184, in <module>
    optparse_main(cmd_obj, argv[1:])
  File "/macqiime/anaconda/lib/python2.7/site-packages/pyqi/core/interfaces/optparse/__init__.py", line 275, in optparse_main
    result = optparse_cmd(local_argv[1:])
  File "/macqiime/anaconda/lib/python2.7/site-packages/pyqi/core/interface.py", line 38, in __call__
    cmd_input = self._input_handler(in_, *args, **kwargs)
  File "/macqiime/anaconda/lib/python2.7/site-packages/pyqi/core/interfaces/optparse/__init__.py", line 194, in _input_handler
    self._optparse_input[optparse_clean_name])
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/interfaces/optparse/input_handler.py", line 42, in load_biom_table
    return parse_biom_table(table_f)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/parse.py", line 310, in parse_biom_table
    t = Table.from_json(json.load(fp), input_is_dense=input_is_dense)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/table.py", line 3602, in from_json
    dtype = MATRIX_ELEMENT_TYPE[json_table['matrix_element_type']]
TypeError: unhashable type: 'list'


#### The same unhashable type:'list' issue

I tried to make a reproducible example with GlobalPatterns, but it gives different error messages, so not sure what is up with that 

#### Code in R

library(phyloseq)
GP <- data("GlobalPatterns")

otu <- as(otu_table(GlobalPatterns), "matrix")
tax <- as(tax_table(GlobalPatterns), "matrix")

b2 <- biomformat::make_biom(data = otu, observation_metadata = tax)

biomformat::write_biom(b2, 'test_GP.biom')

#### Code in macqiime using biom convert

biom convert -i test_GP.biom -o testGP_hdf5.biom --to-hdf5 --table-type="OTU table"

#### Error message
Traceback (most recent call last):
  File "/macqiime/anaconda/bin/pyqi", line 184, in <module>
    optparse_main(cmd_obj, argv[1:])
  File "/macqiime/anaconda/lib/python2.7/site-packages/pyqi/core/interfaces/optparse/__init__.py", line 275, in optparse_main
    result = optparse_cmd(local_argv[1:])
  File "/macqiime/anaconda/lib/python2.7/site-packages/pyqi/core/interface.py", line 38, in __call__
    cmd_input = self._input_handler(in_, *args, **kwargs)
  File "/macqiime/anaconda/lib/python2.7/site-packages/pyqi/core/interfaces/optparse/__init__.py", line 194, in _input_handler
    self._optparse_input[optparse_clean_name])
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/interfaces/optparse/input_handler.py", line 42, in load_biom_table
    return parse_biom_table(table_f)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/parse.py", line 310, in parse_biom_table
    t = Table.from_json(json.load(fp), input_is_dense=input_is_dense)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/table.py", line 3616, in from_json
    input_is_dense=input_is_dense)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/table.py", line 334, in __init__
    self._cast_metadata()
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/table.py", line 489, in _cast_metadata
    self._observation_metadata = cast_metadata(self._observation_metadata)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/table.py", line 483, in cast_metadata
    repr(item))
biom.exception.TableException: Unable to cast metadata: [u'Archaea', u'Crenarchaeota', u'Thermoprotei', None, None, None, None]

#### Just trying to write the otu table alone gives a different error

write_biom(otu, "test_GP2.biom")

biom convert -i test_GP2.biom -o testGP2_hdf5.biom --to-hdf5 --table-type="OTU table"

#### Error 

Traceback (most recent call last):
  File "/macqiime/anaconda/bin/pyqi", line 184, in <module>
    optparse_main(cmd_obj, argv[1:])
  File "/macqiime/anaconda/lib/python2.7/site-packages/pyqi/core/interfaces/optparse/__init__.py", line 275, in optparse_main
    result = optparse_cmd(local_argv[1:])
  File "/macqiime/anaconda/lib/python2.7/site-packages/pyqi/core/interface.py", line 38, in __call__
    cmd_input = self._input_handler(in_, *args, **kwargs)
  File "/macqiime/anaconda/lib/python2.7/site-packages/pyqi/core/interfaces/optparse/__init__.py", line 194, in _input_handler
    self._optparse_input[optparse_clean_name])
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/interfaces/optparse/input_handler.py", line 42, in load_biom_table
    return parse_biom_table(table_f)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/parse.py", line 313, in parse_biom_table
    t = Table.from_tsv(fp, None, None, lambda x: x)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/table.py", line 3824, in from_tsv
    t_md_name) = Table._extract_data_from_tsv(lines, **kwargs)
  File "/macqiime/anaconda/lib/python2.7/site-packages/biom/table.py", line 3940, in _extract_data_from_tsv
    md_name = header[-1]
IndexError: list index out of range


#####

The issue with my current .biom file still giving the same unhashable type:'list' error is my top interest though. Any insight into why this is still giving an error?

I'm running the github biomformat

> packageVersion("biomformat")
[1] ‘1.5.0’

Thanks,

Carly

**Comment by cedwardson4** [comment] 2018-04-17 22:26
Carly,
I'm struggling with various issues of getting from R to qiime/qiime2 as well.

First,
The current github version is 1.7.0.
> packageVersion("biomformat")
[1] ‘1.7.0’

With this version I was able to convert the OTU table only to a correct HDF5 biom file, however I had to transpose my OTU table first (rows=OTUs, columns=samples).

>otu_t <- t(as(otu_table(fnm_cfa), "matrix"))

However, OTU tables with taxonomy are a different story. You may want to try with the biom convert with the "--process-obs-metadata taxonomy" flag, however this did not work for me...

You may want to take a look at:
https://forum.qiime2.org/t/exporting-dada2-r-package-results-to-work-with-qiime2/2573/3

If you don't have dada2 data, the steps should be similar:

in R:
>write.table(t(otu)), "otu_table.txt", sep="\t", row.names=TRUE, col.names=NA, quote=FALSE)

or

>write.table(otu_t)), "otu_table.txt", sep="\t", row.names=TRUE, col.names=NA, quote=FALSE)

Then add a header and convert:

echo -n "#OTU Table" | cat - otu_table.txt > biom-table.txt

biom convert -i biom-table.txt -o table.biom --table-type="OTU table" --to-hdf5
